### PR TITLE
CI: Switch to latest Ubuntu (focal)

### PR DESCRIPTION
**Pull request by pastewka**
Fixes issues with installing muFFT

### CODE REVIEW

**Comment by AntoineSIMTEK** [comment]
https://travis-ci.com/github/ComputationalMechanics/ContactMechanics/jobs/490997438

Now H5 creates so many warnings at compilation that the CI can't stand the 50000 lines of log. 

I guess we need to install a newer version of H5. Any problems with that ?

**Comment by pastewka** [comment]
No, try to switch to a newer version. We need to get rid of this dependency at some point anyway. (All I/O should then go through muGrid's parallel I/O)

**Comment by AntoineSIMTEK** [comment]
Ok I have set it to 0.12.0

**Comment by pastewka** [comment]
muFFT?

**Comment by AntoineSIMTEK** [comment]
No HDF

**Comment by pastewka** [comment]
Okay, you mean 5.12.0...

**Comment by AntoineSIMTEK** [comment]
Yes sorry, 1.12.0

https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.12/

**Comment by pastewka** [comment]
Can you merge this or should I merge it @AntoineSIMTEK

**Review by AntoineSIMTEK — APPROVED** [review]

**Comment by AntoineSIMTEK** [comment]
I think I can do it once both tests have passed.

**Comment by AntoineSIMTEK** [comment]
I will apply the same changes all over the repositories ...

**Comment by pastewka** [comment]
Sounds good!

**Pull request merged**
